Adjust historical price data
Glyphack/pytse-client pull request #122
Opened 2021-09-11 12:56 UTC by alised

افزودن تعدیل عملکردی به کلاس تیکر

نحوه استفاده:
ticker = tse.Ticker(symbol="بركت", adjust=True)

@TODO
افزودن تعدیل  عملکردی به کلاس دانلود
@TODO
ذخیره داده های تعدیل عملکردی جهت کاهش زمان محاسبات

2021-09-12 13:04 UTC, Glyphack commented
سلام خیلی ممنونم برای وقتی که گذاشتید کد رو حتما نگاه میکنم فقط میشه الگوریتیمی که برای تعدیل استفاده شده رو توضیح بدید؟
از چه منابعی استفاده میکنه و الان تعدیلی که انجام میده با قیمت تعدیل شده‌ی سایت‌های دیگه برابر هست آیا؟

2021-09-12 14:20 UTC, alised commented
سلام خواهش می کنم
از روش تعدیل عملکردی استفاده شده است. پس از افزایش سرمایه یا تغییر سود در سایت فناوری اطلاعات قیمت دیروز تعدیل میشود. مثلا اگر سهمی با قیمت پایانی ۲۰۰ تومان بسته شده باشد و ۱۰ تومان سود تقسیم کند در روز بازگشایی قیمت دیروز ۱۹۰ می شود از این نسبت میتوان قیمت های قدیمی را تعدیل کرد. به همین شکل در مورد افزایش سرمایه نیز قیمت دیروز تعدیل می شود.

در این الگورتیم ابتدا روزهای کلیدی مشخص می شود یعنی روزهایی که قیمت دیروز در روز بازگشایی با قیمت پایانی روز قبل از بازگشایی برابر نیست. سپس نسبت آنها محاسبه شده و تمامی قیمت های قبل از این تاریخ در این نسبت ضرب می شوند.

2021-09-12 17:36 UTC, alised commented
در مورد عملکرد برنامه اگر از خطای ناشی از نبود دیتای برخی روزها صرف نظر کنیم (الگوریتم بدلیل خالی بودن یک روز و تفاوت در قیمت دیروز و پایانی اقدام به تعدیل می کند) فرقی با تعدیل عملکردی سایت های دیگه ندارد. 
در برخی سهم ها نیز بدون هیچ دلیل قانع کننده ای قیمت دیروز با قیمت پایانی متفاوت است مثلا در نماد نوری در تاریخ های زیر این تفاوت وجود دارد شاید بدلیل باطل شدن برخی از معاملات رخ داده باشد.

در نماد نوری الگوریتم تاریخ های تعدیل زیر را شناسایی کرده است
2019-07-27 1398-05-05
2020-05-26 1399-03-06
2020-05-30 1399-03-10
2020-07-11 1399-04-21
2020-12-13 1399-09-23
2021-02-17 1399-11-29
2021-07-13 1400-04-22

که تاریخ های 
2020-05-26 1399-03-06
2020-05-30 1399-03-10
بدون دلیل قیمت دیروز و پایانی یکسان نیست

و در تاریخ 
2021-02-17 1399-11-29
دیتای این روز جا افتاده و در خروجی اکسل وجود ندارد در حالیکه در سابقه معاملات وجود دارد این مورد در کلاینت رایگان فناوری اطلاعات بورس وجود دارد.

در ۴ تاریخ دیگر افزایش سرمایه یا تقسیم سود رخ داده است.

2021-09-12 17:59 UTC, alised commented
اگر دیتای روز
2021-02-17 1399-11-29
را به فایل دیتا اضافه کنیم خروجی الگوریتم با دیتای تعدیل شده سایت سهامیاب کاملا یکسان است.

در کل به این شیوه تعدیل کردن تعدیل عملکردی گفته می شود و مشکلاتی که در دیتای سایت فناوری اطلاعات دیده میشود برای همه یکسان است.

2021-09-14 12:59 UTC, alised commented
خیلی عجیبه امروز چک کردم برای نماد نوری گاهی دیتای روز
2021-02-17 1399-11-29
وجود دارد گاهی نیست ؟! واقعا نمیدونم چه اتفاقی افتاده است. برای اطمینان خروجی اکسل از خود سایت فناوری اطلاعات بورس گرفتم و بررسی کردم.
جالبه که دیروز قیمت حداکثر و حداقل روز کاری بعد هم برابر صفر بود ولی الان درست شده است
2021-02-20 

برای رفع این مشکلات نمیشه کاری کرد ولی در هنگام بررسی عملکرد برنامه و مقایسه با سایت های دیگر این موارد را مدنظر قرار دهید.

2021-09-14 20:08 UTC, alised commented
دلیل خاصی داشتید که اندیس دیتافریم را در فایل ذخیره می کنید؟
اگر حذف شود مشکلی در بخش های دیگر برنامه ایجاد می کند؟
یا اینکه بعد از تغییر ترتیب دیتافریم بصورت صعودی (تاریخ) اندیس دیتافریم را ریست نکرده اید؟
الان اگر از وب دیتا بگیریم اندیس ها از نزولی است اگر از فایل بخوانیم صعودی است.

به نظرم بهتر است ستون اندیس در فایل اکسل ذخیره نشود و در هنگام دریافت از وب بعد از مرتب کردن اطلاعات اندیس ها نیز ریست شوند.

2021-09-16 13:46 UTC, Glyphack commented
@alised نه این مشکل اندیس از قصد نبوده و اشکال داره باید درست بشه
من پول ریکوئست رو جمعه یا شنبه نگاه میکنم

2021-09-18 15:58 UTC, Glyphack requested changes
پیاده سازی عالی بود من یه سری کامنت گذاشتم فقط برای اینکه بعضی چیزارو یه تغییر کوچیک بدیم.

2021-09-18 15:58 UTC, Glyphack commented on pytse_client/download.py
> +    adjust: bool = False,
برای اینکه این تغییر کد کسی رو خراب نکنه که نیاز به تغییر داشته باشه بهتر هست که ورودی جدید آخرین ورودی تابع باشه

2021-09-18 15:58 UTC, Glyphack commented on pytse_client/download.py
> +            if(adjust):
این رو میشه به این شکل داشت مرسوم تره
```
if adjust:
```

2021-09-18 15:58 UTC, Glyphack commented on pytse_client/download.py
>              if write_to_csv:
زمانی که یوزر دیتای تعدیل شده بخواد ما بهش تعدیل شده رو توی خروجی میدیم و زمانی ولی هم تعدیل شده و هم تعدیل نشده رو توی فایل مینویسیم بنظرم خروجی هر دو قسمت یکی باشه بهتره. یعنی زمانی که تعدیل شده رو خواست هم تعدیل شده رو برگردونیم هم تعدیل شده رو توی فایل ذخیره کنیم

2021-09-18 15:58 UTC, Glyphack commented on pytse_client/download.py
> +    if(df.empty == False and isinstance(df.index, pd.core.indexes.range.RangeIndex)):
برای اینکه کل تابع توی یک ایف نباشه و کد ایندنت نشه میشه این شرط رو برعکس نوشت به این شکل
```
if not(df.empty == False and isinstance(df.index, pd.core.indexes.range.RangeIndex)):
    return
```

2021-09-18 15:58 UTC, Glyphack commented on pytse_client/download.py
> +def adjust_price(df):
این تابع بهتره که خود دیتافریم رو تغییر ندیم و یه دیتافریم جدید بسازیم. و برگردونیم

2021-09-18 15:58 UTC, Glyphack commented on pytse_client/ticker/ticker.py
> +        self.adjust_csv_path = f"{config.DATA_BASE_PATH}/{self.symbol}-ت.csv"
من اینجا زمانی که این متغیر
csv_path
رو درست کردم خیلی اسم دقیقی نزاشتم الان که میبینم بهتره این اسم بیشتر توضیح بده که چی رو نگه میداره
اسمش رو بزاریم
adjusted_daily_records_csv_path
؟

2021-09-18 15:58 UTC, Glyphack commented on pytse_client/ticker/ticker.py
> +    def __init__(self, symbol: str, index: Optional[str] = None, adjust: bool = False, write_to_csv: bool = False,):
اینجا ورودی 
write_to_csv
رو میتونیم نداشته باشیم چون که فرض  استفاده بر اینه که اگر کسی میخواد دیتای خروجی بگیره تابع  درست همون
download هست
ممکنه این رو بزاریم و یوزر اشتباه کنه توی استفاده صحیح

2021-09-18 15:58 UTC, Glyphack commented on pytse_client/download.py
> +        diff = list(df.index[df.shift(1).adjClose != df.yesterday])
راستش بهتر اینجاهارو یه سری کامنت داشته باشیم که چرا داریم مثلا این کار رو میکنیم. اگر کسی بعدا بخواد روی کد تغییراتی بده این کمک میکنه بهش

2021-09-18 19:53 UTC, alised commented on pytse_client/download.py
> +def adjust_price(df):
دلیلی برای این کار نمی بینم چون بعد از تغییر داده‌ها تنها آن را ذخیره و به کاربر برمیگردانیم و دیگر دیتای اصلی کاربردی ندارد و صرفا کپی گرفتن از دیتافریم مصرف حافظه را افزایش میدهید. اگر دلیل خاصی مد نظرتان است لطفا بیشتر توضیح دهید

2021-09-18 20:03 UTC, alised commented on pytse_client/download.py
> +        diff = list(df.index[df.shift(1).adjClose != df.yesterday])
منظورتان الگوریتم تعدیل قیمت است؟
یا شرط 
isinstance(df.index, pd.core.indexes.range.RangeIndex)
یا خط
step = df.index.step

2021-09-19 05:53 UTC, Glyphack commented on pytse_client/download.py
> +def adjust_price(df):
<div dir="rtl">
این فقط به خاطر این هست که تابعی که ورودی رو
mutate 
می‌کنه یکم سخت‌تر میکنه خوندن کد رو و به خاطر همینم اکثر توابع pandas و spark هر تغییری میخوان بدن روی یه دیتافریم جدید میدن
مثلا
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.transform.html
</div>

2021-09-19 06:01 UTC, Glyphack commented on pytse_client/download.py
> +        diff = list(df.index[df.shift(1).adjClose != df.yesterday])
<div dir="rtl">
این توضیح کاملی بود آره توضیح خط به خط تأثیری نداره ولی مثلا همین نکته که diff چی هست و چرا انجامش میدیم رو هرکسی نمیدونه
بنظرم مشکلی نداره همین رو مرج کنیم با این کامنت
</div>

2021-09-19 06:06 UTC, Glyphack commented
این ارور های استایل چک رو میتونی چک کنی؟

2021-09-19 08:46 UTC, alised commented
چند مورد خطا در طول خطوط وجود داره اگر پیشنهادی دارید بفرمایید روشی که خوانا باشه به ذهنم نمیرسه

2021-09-19 19:30 UTC, merged

2021-09-19 19:30 UTC, Glyphack commented
با تشکر از زحمات شما @alised

2021-11-26 19:39 UTC, mostafa2msh commented
سلام من از این کد استفاده میکنم اما خطا میده لطفا بررسی بفرمائید
ticker = tse.Ticker(symbol="بركت", adjust=True)
TypeError: __init__() got an unexpected keyword argument 'adjust'