Merge records of old instrument indexes to new one
Glyphack/pytse-client pull request #129
Opened 2021-09-19 23:42 UTC by alised

بروزرسانی فایل جیسون به همراه آیدی نمادهای حذف شده

در جدول تحت وب به اشتباه نماد حذف شده وجود دارد که مشکل ایجاد می کرد نمادهایی که با حذف شروع می شوند را حذف کردم البته دارید روش کار می کنید

دریافت تاریخچه قیمت نماد جدید و قدیم و ترکیب آنها با هم

در صورتی که نمادی در لیست جیسون نباشد و کاربر مستقیما نماد آن را در تابع دانلود درج کند برنامه بعد از جستجو
آن نماد را به لیست جیسون اضافه کرده و تاریخچه قیمت را به کاربر بر می گرداند

مرتب سازی نمادها قبل از ذخیره در فایل جیسون درست عمل نمی کند! نیاز به بررسی دارد

2021-09-22 16:06 UTC, Glyphack commented
خیلی ممنون این رو فردا یا پس فردا نگاه میکنم

2021-09-22 16:48 UTC, alised commented
@Glyphack 
خواهش می کنم. 
بررسی کنید اگر فکر می کنید ایده خوبیه جستجو را بصورت همزمان انجام بدیم که زمان کمتری ببره
من نگران اینم که آیپی کاربر بلاک شود.

2021-09-25 12:59 UTC, Glyphack requested changes

2021-09-25 12:59 UTC, Glyphack commented on pytse_client/download.py
> +        raise Exception(f"{symbol_name}: Sorry, tse server did not respond")
ما اینجا یه اکسپشن ریز میکنیم ولی بالاتر که این تابع صدا شده اکسپشن رو نمیگیریم یه نظر دیگه دارم برای این کار.
ما اینجا اکسپشن ریز کنیم ولی دیگه نان برنگردونیم یعنی یا تابع مقدار مورد نظر رو بده یا یه اکسپنش و در تابعی که این رو صدا میکنه چک کنیم اگر  اکسپنشی داشتیم یعنی خطا داشتیم و اونو نشون بدیم اگر نه که به کار ادامه بدیم

2021-09-25 12:59 UTC, Glyphack commented on pytse_client/download.py
> +        raise Exception(f"{symbol_name}: Sorry, tse server did not respond")
و اینکه اینجا مشکلی هم نداره اگر همون خود ریکوئست ارور ریز کنه و ما همونو بفرستیم

2021-09-25 12:59 UTC, Glyphack commented on pytse_client/download.py
>                  ticker_index = symbols_data.get_ticker_index(symbol)
اگر میشه اینجارو یکم ریفکتور کنیم بنظرم از اول این کد پیچیده بود خوندنش
ما اینجا ایندکس رو از فایل بخونیم اگر نان بود تابع بعدی رو صدا کنیم برای اینکه ایندکس رو از اینترنت بگیریم. یعنی توی تابع بعدی دیگه ایف نان بودن رو نداشته باشیم.

2021-09-25 12:59 UTC, Glyphack commented on pytse_client/download.py
> +                ).replace('\u200c', '')
نیم فاصله رو باید حذف کنیم؟

2021-09-25 12:59 UTC, Glyphack commented on pytse_client/download.py
> +            if(symbol_full_info[7] == '1'):
اینجا یه کامنت باشه که توضیح بده این شرط یعنی چی خوب هست

2021-09-25 12:59 UTC, Glyphack commented on pytse_client/scraper/symbol_scraper.py
> +def get_old_index_of_market_symbols(
با کاری که این تابع میکنه بنظرم اسمش رو تغییر بدیم
add_old_indexes_to_market_symbols

2021-09-25 13:00 UTC, Glyphack commented
> @Glyphack
> خواهش می کنم.
> بررسی کنید اگر فکر می کنید ایده خوبیه جستجو را بصورت همزمان انجام بدیم که زمان کمتری ببره
> من نگران اینم که آیپی کاربر بلاک شود.

بنظرم جستجو همینطوری باشه مشکلی نداره چون این جستجو هم فقط زمانی که میخوایم فایل رو پر کنیم انجام میشه نه همیشه

2021-09-25 13:36 UTC, alised commented on pytse_client/scraper/symbol_scraper.py
> +                name=replace_arabic(data[3]).replace('\u200c', ''),
از پذیرش سازمان بورس بپرسید چرا توی نماد نیم فاصله درج می کنند. در برخی نمادها ابتدا یا انتهای انها نیم فاصله درج شده است
داخل فایل جیسون هم سرچ کنید می بینید که برخی نمادها دارای نیم فاصله هستند که باعث این مشکل میشود کاربر نام نماد را درج می کند تا دیتا دریافت کنی ولی خطا دریافت می کند که این نماد وجود ندارد

2021-09-25 18:38 UTC, alised commented on pytse_client/download.py
> +        raise Exception(f"{symbol_name}: Sorry, tse server did not respond")
دو تا اکسپشن داریم
اکسپشن داخل این تابع مربوط به ریسپانس کد است
اما ممکنه اطلاعات مورد نظر داخل پاسخ وجود نداشته باشد که نان برمیگردانیم
اما چرا در اینجا اکسپشنی برای نان بودن بر نگردانم چون اینجوری دست برنامه نویس بازه در فراخوانی این تابع شاید بخواد برنامه به کار خود ادامه بده و تنها به دادن اخطار به کاربر بسنده کند

اگر بخواهیم در اینجا اکسپشن ریز کنیم باید یک کاستم اکسپشن برای نان بودن نماد بسازیم که در هنگام فراخوانی بتونیم بگیریمش و حالا یا برنامه را متوقف کنیم یا با دادن اخطار ادامه بدیم
_handle_ticker_index

برای اینکه کاربر متوجه شود که نام چه نمادی را اشتباه تایپ کرده است ریکوئست ارور را کچ کردم چون ممکنه کاربر آرایه ای از نمادها را دانلود کند. البته باید در تابع بالایی هم خطا اصلاح شود.

چون تغییرات این بخش زیاد بود سعی کردم از ساختار موجود پیروی کنم این تابع بسیار مشابه تابع زیر است
get_symbol_id

2021-09-25 18:41 UTC, alised commented on pytse_client/download.py
>                  ticker_index = symbols_data.get_ticker_index(symbol)
خب شاید تابع بعدی هم نان برگرداند. اگر موافقید از یک تابع استفاده کنیم که همه این خطوط را در خود جای دهد و بعدش فقط یک بار نان بودن را چک کنیم؟

2021-09-25 19:15 UTC, Glyphack commented on pytse_client/download.py
>                  ticker_index = symbols_data.get_ticker_index(symbol)
آره درسته ولی بهرحال ما الان داریم دوتا ایف رو مینویسیم.بنظرم اشکالی نداره اینجا به وضوح چک کنیم چیزی رو که میخوایم رو با وجود اینکه دوبار چک میشه. راه حل یه تابع داشتن هم خوبه هرکدوم بنظرت بهتر در میاد رو بنویسیم.

2021-09-25 19:15 UTC, alised commented on pytse_client/download.py
> +                ).replace('\u200c', '')
الان نماد مشکل دار ندیدم ولی موقع کار چند تا نماد نیم فاصله داشتند.
بررسی که کردم در منبع زیر نماد دتهران به نیم فاصله ختم میشه
MarketWatchInit
ولی در جستجو هم نمادهایی این مشکل را داشتند خاطرم نیست چی بود
میتونیم نیم فاصله را تریم کنیم بجای ریپلیس

2021-09-25 19:16 UTC, alised commented on pytse_client/download.py
> +                ).replace('\u200c', '')
یا ببریم توی تابع زیر چون داخلش دستور استریپ هم دارد
replace_arabic

2021-09-25 19:17 UTC, Glyphack commented on pytse_client/download.py
> +        raise Exception(f"{symbol_name}: Sorry, tse server did not respond")
متوجهم میتونیم این بخش رو اینجا دست نزنیم بعدا ریفکتور بشه. الان دیدم که از قبل به این شکل بوده.

2021-09-25 19:18 UTC, alised commented on pytse_client/download.py
> +            if(symbol_full_info[7] == '1'):
پایان ایف نوشته شده بود ولی کلی کد به اولش اضافه شد برای همین اضافه کردم کامنت را

2021-09-25 19:21 UTC, Glyphack commented on pytse_client/scraper/symbol_scraper.py
> +                name=replace_arabic(data[3]).replace('\u200c', ''),
چه کار عجیبی میکنن.  ایده‌ی خوبیه فقط پس اگر این کار رو میکنیم میشه  یه تابع درست کنیم که هم کاراکتر عربی رو جایگزین کنه هم نیم فاصله رو برداره؟ اینطوری همیشه باید یادمون باشه دوتا تابع رو صدا کنیم.
اسمش هم میتونه
normalize_name_from_tse
باشه مثلا

2021-09-25 20:34 UTC, alised commented
باید در بروزرسانی فایل جیسون توجه کنیم که دو منبع مورد استفاده نمادهای متوقف را شامل نمی شوند. یعنی اگر نمادی برای چند روز هم بسته باشد داخل این لیست ها نمی آید

2021-09-25 20:37 UTC, alised commented on pytse_client/scraper/symbol_scraper.py
> +                name=replace_arabic(data[3]).replace('\u200c', ''),
فعلا بردم داخل تابع اربیک چون تریم کردن فاصله و نیم فاصله هیچ مشکلی ایجاد نمیکنه

2021-09-25 20:57 UTC, alised commented on pytse_client/download.py
>                  ticker_index = symbols_data.get_ticker_index(symbol)
اینجا قبلا اینطوری بود که هندل داخل ایف بود به ریز اکسپشن داخل هندل دقت نکردم اصلا به ایف نان نیازی نیست
حالا اگر همه چیز را داخل تابع هندل مدیریت کنیم خوانایی کد بیشتر نمی شود؟
یا فکر می کنید ریز اکسپشن را بیاریم داخل تابع دانلود و از هندل حذف کنیم خوانا تر میشود؟

2021-09-25 21:26 UTC, alised commented on pytse_client/download.py
> +                    raise Exception(f"Cannot find symbol: {symbol}")
ترجیح دادم تابع جدیدی اضافه نکنم
اینجا اکسپشن ریز بشه برنامه خواناتر میشه تا اینکه توی تابع هندل باشه
اگر موافقید کمی کد را خلاصه تر کنیم به نحوی که تابع هندل لیستی از اندیسهای نماد را برگرداند

2021-09-25 21:56 UTC, alised commented on pytse_client/download.py
>                  ticker_index = symbols_data.get_ticker_index(symbol)
ترجیح دادم تابع جدیدی اضافه نکنم
اینجا اکسپشن ریز بشه برنامه خواناتر میشه تا اینکه توی تابع هندل باشه
اگر موافقید کمی کد را خلاصه تر کنیم به نحوی که تابع هندل لیستی از اندیسهای نماد را برگرداند

2021-09-25 22:07 UTC, alised commented on pytse_client/download.py
> +def get_symbol_data(symbol_name: str):
معمولا وقتی تابعی دیتا از اینترنت میگیرد اسمشو با فچ شروع می کنم و اگر از دیتابیس بگیرد با گت
ولی در برنامه همه جا از گت استفاده دشه است و چون این تابع دیتا دریافت می کند بهتر است با گت شروع شود
get_symbol_info
چطوره؟

2021-09-27 15:26 UTC, Glyphack commented on pytse_client/download.py
> +                ).replace('\u200c', '')
آره تریم کنیم فکر خوبیه اگر توی اون تابع میبریم اسمش رو تغییر بدیم چون دیگه ربطی به ریپلیس کردن کاراکترهای عربی نداره

2021-09-28 13:38 UTC, Glyphack approved these changes
همه چیز اوکیه امشب مرج میشه

2021-09-28 14:05 UTC, alised commented
> همه چیز اوکیه امشب مرج میشه

نام تابع را پرسیدم جواب ندادید به همان نام پیشنهادی تغییر دادم
get_symbol_info

برای تصحیح نماد یا نام شرکت چرا نیم فاصله از نام شرکت حذف شده است؟

2021-09-28 17:50 UTC, Glyphack commented
> > همه چیز اوکیه امشب مرج میشه
> 
> نام تابع را پرسیدم جواب ندادید به همان نام پیشنهادی تغییر دادم get_symbol_info
> 
> برای تصحیح نام شرکت چرا نیم فاصله از نام شرکت حذف شده است؟ بهتره نیم فاصله با فاصله جایگزین شود سپس دو فاصله یا بیشتر به یک فاصله کاهش یابد و تریم شود

آره اسم اوکی هست بعدا هم اگر چیز بهتری پیدا بشه میشه تغییر داد چون چیزی رو خراب نمیکنه.
برای نیم فاصله هم این قانون اوکی هست فقط این رو هم پس به توضیحات پروژه اضافه کنید که بقیه بدونن اسم رو چطوری باید وارد کرد.

2021-09-28 18:38 UTC, alised commented
> برای نیم فاصله هم این قانون اوکی هست فقط این رو هم پس به توضیحات پروژه اضافه کنید که بقیه بدونن اسم رو چطوری باید وارد کرد.

منظورم اسم شرکت بود نه نماد. در مورد نماد فقط تریم می کنیم و نیازی نیست کاربر موردی را لحاظ کند
برای اسم شرکت متوجه نشدم کدام قانون اوکی است؟ چیزی که داخل کد است یا چیزی که پیشنهاد دادم. داخل کد کنونی نیم فاصله از کل اسم شرکت حذف می شود که باعث چسبیدن لغات برخی شرکت ها به هم میشود. (متاسفانه در برخی نمادها از فاصله و نیم فاصله در جای خود استفاده نشده است)

اگر موافقید این برنچ را ببندیم بقیه تغییرات بعدا اعمال شود

2021-09-28 20:06 UTC, Glyphack commented
آره موردی نداره تغییرات این برنچ هم زیاد هست اسم شرکت رو بعد از این تغییر میدیم

2021-09-28 20:06 UTC, merged

2021-09-28 20:12 UTC, Glyphack commented
ممنون بابت کانتریبیوشن

2021-09-29 09:03 UTC, alised commented
خواهش می کنم