Alised fix last price and get all ticker data
Glyphack/pytse-client pull request #138
Opened 2021-10-17 14:29 UTC by alised

دریافت تمامی اطلاعات روز نماد از جمله حجم معاملات و وضعیت نماد #137 
رفع باگ:  قبلا برای قیمت آخر و پایانی بر اساس فاصله اسپلیت انجام میشد در حالیکه باید اول از نقطه ویرگول برای اسپلیت استفاده شود سپس ویرگول.
مشکل وقتی ایجاد میشود که وضعیت نماد بسته است. در حالتی که نماد باز است وضعیت آن
"A "
می باشد ولی وقتی نماد بسته است وضعیت
"AS"
می باشد در این حالت دیگر در متن فاصله ای وجود ندارد و خطای اندیس داریم لذا قیمت پایانی و آخرین معامله نان می‌شود

سوال: در متن نوشته اید که گاهی بجای قیمت پایانی حرف اف انگلیسی می آید میتوانید نمادی را مثال بزنید که این مشکل را دارد؟

2021-11-01 17:49 UTC, Glyphack commented
سلام
من درباره اون حالت که جای قیمت حرف اف قرار داده میشه الان یادم نمیاد مثالی و نمیتونم تست کنم. اگر شما این حالت رو دیدید که با همین کد پیش بریم اگر نه اون خطی که اون کد هندل کردن ارور برای اف رو میتونیم برداریم تا زمانی که این ارور پیش اومد ببینیم.

2021-11-01 17:52 UTC, Glyphack requested changes
بقیه چیز‌ها خوب هست فقط دوتا نکته
لطفا این قابلیت‌های جدید رو توی 
readme
پروژه بنویسید اگر توی مثال‌ها هم وارد بشه بهتره
یک فایل وجود داره که تست میکنه این توابع رو این قابلیت‌های جدید رو هم توی اون وارد کنید
https://github.com/Glyphack/pytse-client/blob/9795b5aa55c587dba973080cda36d74edae62d5d/tests/test_ticker/ticker_e2e.py

2021-11-01 19:17 UTC, alised commented
> سلام من درباره اون حالت که جای قیمت حرف اف قرار داده میشه الان یادم نمیاد مثالی و نمیتونم تست کنم. اگر شما این حالت رو دیدید که با همین کد پیش بریم اگر نه اون خطی که اون کد هندل کردن ارور برای اف رو میتونیم برداریم تا زمانی که این ارور پیش اومد ببینیم.

سلام نه من حالت اف ندیدم تا حالا.

2021-11-01 19:30 UTC, alised commented
> بقیه چیز‌ها خوب هست فقط دوتا نکته لطفا این قابلیت‌های جدید رو توی readme پروژه بنویسید اگر توی مثال‌ها هم وارد بشه بهتره یک فایل وجود داره که تست میکنه این توابع رو این قابلیت‌های جدید رو هم توی اون وارد کنید https://github.com/Glyphack/pytse-client/blob/9795b5aa55c587dba973080cda36d74edae62d5d/tests/test_ticker/ticker_e2e.py

مواردی که آوردم همه زیر مجموعه این تابع است
`print(ticker.get_ticker_real_time_info_response()) # اطلاعات لحظه‌ای مانند قیمت و پیشنهادات خرید و فروش
`
بنابراین نیازی به آوردن در توضیحات یا بخش تست نیست
مگر اینکه برای تک تک موارد اضافه شده پراپرتی جداگانه تعریف بشه به نظرم اینکار بهتر است چون برای آیتم های قبلی این تابع انجام شده است اگر موافقید انجام بدم
مانند:
`    @property
    def last_price(self):
        return self.get_ticker_real_time_info_response().last_price

    @property
    def adj_close(self):
        return self.get_ticker_real_time_info_response().adj_close

    @property
    def best_demand_vol(self):
        return self.get_ticker_real_time_info_response().best_demand_vol
`

2021-11-01 20:14 UTC, alised commented
در مورد قیمت پایانی و بقیه اگر مقداری غیر عددی باشد یا حتی متن خالی باشد خطا خواهیم داشت پس بهتره خطا کچ بشه. هرچند حالتی که متن خالی باشه هم به چشمم نخورد.

2021-11-01 20:19 UTC, alised commented
وقتی دیتای قیمتی بصورت پراپرتی دریافت می شود برای تک تک آنها یک درخواست به سایت میفرستد که کارا نیست.
به همین دلیل بهتر است از تابعی که همه را با هم دریافت می کند استفاده شود. یا دیتای این تابع برای یک ثانیه کش شود که اگر قیمت ها با استفاده از پراپرتی و پشت سرهم آمد مشکل بن شدن آیپی و خطای تایم اوت نداشته باشیم.

2021-11-02 06:26 UTC, Glyphack commented
بنظرم میشه ریسپانس رو کش کنیم فقط یه چیزی رو مطمئن نیستم اگر ما این رو برای یک ثانیه کش کنیم اونوقت کاربر بیشتر از یکبار در ثانیه اطلاعات مفید نمیتونه بگیره. این چقدر اینجا مهم هست؟ در کل یعنی اون بازه‌ای که این صفحه رو ما از کش جواب میدیم اطلاعات مهمی نیست که از دست بره؟

2021-11-02 07:21 UTC, alised commented
به نظرم تعداد معاملات در سهام پر معامله گزینه خوبی برای بررسی است.
هدفم این است که آیا سایت دیتا را کش می کند برای زمان کوتاهی یا دیتا لحظه ای است هرچند تعداد معاملات یکی یکی افزایش نمیابد چون ممکن است چند معامله در یک لحظه و با هم رخ دهد. بنابراین فقط تغییرات صعودیش را میتوان بررسی کرد.
ظاهرا دیتا هر بار از سرور متفاوتی دریافت شود مقادیر بالا پایین میشود با وجود اینکه تعداد معاملات باید صعودی باشد
بنابراین در حالتی که از پراپرتی استفاده می کنیم ممکن است اطلاعات مربوط به یک لحظه خاص نباشد مثلا تاریخ با قیمت پایانی هماهنگ نیست.
در مورد مشکلاتی که سینک نبودن دیتا میتواند ایجاد کند چیزی به ذهنم نمیرسه ممکن است خیلی کم اهمیت باشد و فقط همان بحث کارایی مطرح باشد.
در نهایت می توان صرفا به یک نکته در داکیومنت بسنده کرد با این مذمون که در صورت نیاز به بیش از یک مورد از دیتای لحظه ای بهتر است از تابع زیر استفاده کنید تا هم تعداد دفعات درخواست از سایت کاهش یابد  و هم دیتای قیمت و تاریخ مرتبط با هم باشند:
get_ticker_real_time_info_response()

x = tse.Ticker('برکت')
for i in range(0,100):
    print(x.count)

[out]
11688
11688
11688
11703
11703
11688
11688
11703
11703
11688
11703
11703
11703
11703
11703
11703
11703

2021-11-02 09:52 UTC, Glyphack commented
خیلی ممنون بابت کد و بررسی‌ای که انجام دادید

2021-11-02 09:52 UTC, merged