Add financial index feature as in #26 discussed
Glyphack/pytse-client pull request #155
Opened 2022-03-07 06:35 UTC by sfmqrb

#26 fixed!
I also add some documentation to README.md file.

2022-03-08 07:19 UTC, Glyphack requested changes
خیلی ممنونم برای وقتی که گذاشتید من یه پیشنهاد دارم که این فیچر شاخص رو از نمادها جدا کنیم که توابع ساده تر باشه کار باهاشون(آرگومنت‌های کمتر، if های کمتر و کلا scope کوچیکتر) یه بدیش اینه که یه مقدار کد duplicate اضافه میشه ولی اونو میشه بعدا ریفکتور کرد. اما الان اگر بخوایم فیچر جدیدی برای شاخص یا نمادها اضافه بکنیم باید یه تابع رو تغییر بدیم و این خیلی با [single responsibility principle](https://cleancoders.com/episode/clean-code-episode-9) جور در نمیاد

2022-03-08 07:19 UTC, Glyphack commented on pytse_client/download.py
> +    isIndex: bool = False
اگر موافقید تابعی که شاخص رو میگیره از این جدا کنیم. فعلا اشکالی نداره که حتی تا حد زیادی کپی باشه بعدا میشه ریفکتور کرد. چون ممکنه توی بلند مدت این دوتا فیچر جدا آپشن‌های جدا داشته باشن و این تابع خیلی شلوغ بشه.

2022-03-08 07:19 UTC, Glyphack commented on pytse_client/download.py
> +    dates = data[::2]
اینجا بهتره که چک بشه این دیتا در اون صفحه وجود داشته و خالی نیست وگرنه اروری که میده واضح نیست چی شده

2022-03-08 07:19 UTC, Glyphack commented on pytse_client/download.py
> +    if isIndex:
اگر تابع هارو جدا کنیم دیگه این if هم نیاز نداریم

2022-03-08 07:19 UTC, Glyphack commented on pytse_client/symbols_data.py
> +def symbols_information(isIndex: bool = False) -> Dict[str, Dict]:
بنظرم اینجا تابع گرفتن ایندکس شاخص و سهام‌هارو جدا کنیم چون در نهایت خیلی باعث if نوشتن میشه و خوندن کد سخت تره. موافقید؟

2022-03-08 07:40 UTC, sfmqrb commented on pytse_client/data/generate_indices_name.py
> +        section_number = re.search(r'(^\d+|\d+$)', key)
من این اسم رو قبلا در این پروژه دیده بودم در پروژه این [لینک](https://github.com/m-ahmadi/tse-client) البته اسم section_number رو خودم انتخاب کردم ولی مفهوم همونه.

2022-03-08 07:40 UTC, sfmqrb commented on pytse_client/data/generate_indices_name.py
> +    ls = re.findall(
حتما

2022-03-08 07:43 UTC, sfmqrb commented on pytse_client/data/generate_indices_name.py
> +    for toBeIndex in ls:
حتما

2022-03-08 07:46 UTC, sfmqrb commented on pytse_client/data/generate_indices_name.py
> +        section_number = int(section_number.group(
برای نمادهای شاخصی ای که section_number ندارن منظورتون هست؟
اگر آره هندلش می کنم 
اگر به طور کل پیشنهاد می کنید که حذف شه section_number به نظرم فیچر خوبیه و حیفه
یه کم بیشتر این کامنتتون رو توضیح بدید ممنون میشم یه مقدار برام گنگ بود

2022-03-08 07:49 UTC, sfmqrb commented on pytse_client/download.py
> +    isIndex: bool = False
موافقم منم و اصلا می خواستم همینطور پیاده سازی کنم ولی دیدم که کاربر ها یه تابع download می شناسن و که با همه symbol ها طرفه.
به نظرم خوبه این abstraction طرف ما باشه که بیایم بر اساس نوع symbol تابع مشخصی رو ران بگیریم یعنی اساسا تابع download یه تابع مادر باشه که هر کسی اطلاعات هر symbol از اختبار معامله تا آتی تا ... نیاز داشت به همین تابع رجوع کنه و حالا مثلا با یه فلگی مشخص کنه نیازش رو و بعد ما در داخل این تابع مسئولیت ها رو تقسیم کنیم در توابع دیگری که به شکل دقیقی مسئول اون کار هستند.

2022-03-08 07:50 UTC, sfmqrb commented on pytse_client/download.py
> +    dates = data[::2]
حتما

2022-03-08 07:53 UTC, sfmqrb commented on pytse_client/download.py
> +    if isIndex:
حرفتون درسته و موافقم
ولی فکر می کنم نظرم رو بهتون در دو کامنت بالاتر گفتم
بازم در خدمتتونم البته اگر فکر می کنید لازمه می تونم کلا ببرم در یک تابع دیگه

2022-03-08 07:57 UTC, sfmqrb commented
به طور کل موافق جدا کردن توابع نیستم 
به نظرم برای کاربر در نهایت اینا یه چیزن و تعداد توابع گیجش می کنه 
ولی در خود کد برای maintainer ها کار رو سخت می کنه که توابع مادر و توزیع کننده مسئولیت رو مشخص و تعیین کنن و اون ها رو اون طور که باید تغییر بدن تا کد خوانایی خودش رو از دست نده
این به نظرم از این منظر که در آینده دیتاهای متنوع دیگری رو هم بخوایم در پکیج بگنجونیم برای خودمون و user روش بهتریه.
ولی در کل اوکیم با جدا کردنش هم انجام میدم 👍

2022-03-08 08:04 UTC, sfmqrb commented
یه چیزی هم حس می کنم خوبه بگم
یه مقدار diff-checker git به نظرم بد عمل کرده در تابع download 
توصیه می کنم خود تابع رو از آخرین کامیت مورد بررسی قرار بدید

2022-03-12 13:50 UTC, sfmqrb commented
در نهایت ممنون میشم تصمیم نهایی تون رو بهم بگید که آیا ماژول دریافت اطلاعات نمادهای شاخصی رو ایزوله کنم از ماژول های دریافت اطلاعات غیر شاخصی یا نه

2022-03-12 16:38 UTC, Glyphack commented
من مریض شدم از هفته پیش با یکم تأخیر نگاه میکنم کامنت هارو تا چند روز آینده. مرسی بابت تغییرات.

ولی درباره جدا کردن برای اینکه بتونید کارتون رو پیش ببرید:
تنها دلیلی که بنظرم جدا کردن بهتره اینه که این دوتا تابع دو نوع اطلاعاتی رو میدن به ما که یک شکل هست ولی به شکلی که توی سایت هست یه چیز نیستن مثلا یه قابلیت که این تابع میخواد اضافه بشه #113 هست که برای این من تو ذهنم بود که به تابع یه پارامتر جدید اضافه کنم تایم فریمی که میخوایم قیمت هارو برای اون بازه بگیریم رو داشته باشه، ولی این پارامتر ربطی به کنترل کردن تایم فریم شاخص نداره(میتونیم پیاده بکنیم ولی جدا از اون یکی قابلیت باید پیاده بشه) بخاطر همین ورودی‌های تابع با هم ناسازگار میشن(تایم فریم رو نمیشه همراه با is_index به تابع بدیم اثر نداره). الان کدشون خیلی شبیه هست ولی نوعی که کار میکنن فرق داره و در آینده هرکدوم ممکنه نیاز متفاوتی داشته باشه.

منظورم رو رسوند این مثال؟

2022-03-16 08:16 UTC, sfmqrb commented
> من مریض شدم از هفته پیش با یکم تأخیر نگاه میکنم کامنت هارو تا چند روز آینده. مرسی بابت تغییرات.
> 
> ولی درباره جدا کردن برای اینکه بتونید کارتون رو پیش ببرید: تنها دلیلی که بنظرم جدا کردن بهتره اینه که این دوتا تابع دو نوع اطلاعاتی رو میدن به ما که یک شکل هست ولی به شکلی که توی سایت هست یه چیز نیستن مثلا یه قابلیت که این تابع میخواد اضافه بشه #113 هست که برای این من تو ذهنم بود که به تابع یه پارامتر جدید اضافه کنم تایم فریمی که میخوایم قیمت هارو برای اون بازه بگیریم رو داشته باشه، ولی این پارامتر ربطی به کنترل کردن تایم فریم شاخص نداره(میتونیم پیاده بکنیم ولی جدا از اون یکی قابلیت باید پیاده بشه) بخاطر همین ورودی‌های تابع با هم ناسازگار میشن(تایم فریم رو نمیشه همراه با is_index به تابع بدیم اثر نداره). الان کدشون خیلی شبیه هست ولی نوعی که کار میکنن فرق داره و در آینده هرکدوم ممکنه نیاز متفاوتی داشته باشه.
> 
> منظورم رو رسوند این مثال؟

سلام 

امیدوارم به زودی سلامتی خودت رو کامل به دست بیاری.
متوجه حرفت شدم و جداش میکنم و پوش میکنم.

به نظرم خوبه در ادامه milestone تعریف بشه برای اینکه این تفاوت پشت صحنه دریافت انواع اطلاعات بازار سرمایه از جمله شاخص و سهام و اختیار و ... خودش رو در قالب تعریف توابع جدید برای کاربر نشون نده تاکید دارم برای کاربر. بلکه همه‌شون در قالب یک تابع باشن که به شکلی کار رو برای کاربر راحت تر کنه و حتی با یک تابع بتونه کاربر همه اطلاعات از هر جنس رو بگیره. 
اون نکته ای شما گفتی در مورد تایم فریم یک دقیقه ای تاریحی برای دیتای شاخص هم به عنوان ورودی valid هست البته هنوز راه خوبی براش پیدا نکردم ولی به هر حال براش تعریف میشه و شاید بشه پیدا کرد بعدا یه راهی.

امیدوارم منظورم رو رسونده باشم اگرم سوالی بود درخدمتم.
ممنونم از وقتی که گذاشتی.

2022-03-16 08:31 UTC, Glyphack commented
خیلی ممنونم. آره مخالف این موضوع نیستم در کل ولی تو شرایط حاضر بنظرم کار معقولیه و میشه زمانی که ورژن ۱.۰.۰ رو خواستیم درست کنیم برای این‌ها تصمیم بهتری بگیریم که برای کاربر راحت تر باشه استفاده از توابع مختلف.

2022-03-16 22:20 UTC, sfmqrb commented
@Glyphack 
نکاتی که گفته شده بود رو اعمال کردم.
اگر نکته ای بود حتما در اولین فرصت اعمال می‌کنم.
ممنونم

2022-03-17 19:58 UTC, Glyphack approved these changes
همه چیز خوبه

2022-03-17 21:48 UTC, sfmqrb commented
تقریبا همه اصلاح شدند

2022-03-18 08:46 UTC, merged