آمار های کلیدی
Glyphack/pytse-client pull request #163
Opened 2022-04-19 13:29 UTC by sfmqrb

#160 
توی این pr به ایشوی بالا رسیدگی شده است.
در حال حاضر تمامی آمارهای کلیدی که قابل فهم برای لیست نماد های پکیج در symbols_name.json هستند به صورت یکجا دریافت شده و پروسس می‌شود و در قالب یک خروجی فایل جیسون و یک خروجی دیکشنری با نامگذاری مناسب بر روی فیلدها آماری در اختیار کاربر قرار می‌گیرد.

حقیقت خودم در این فکر بودم که آمارهای کلیدی هر سهم را زیرمجموعه Ticker خودش بیاورم و مخصوص هر سهم به صورت جداگانه فیلدهایی به کلاس Ticker اضافه کنم ولی با توجه به اینکه اگر کسی به قصد فیلترنویسی بخواهد از این آمار ها استفاده کند مطمئنا سریع تر و کم دردسر تر است که یک مجموعه به شکل مستقل دریافت کند از این بابت آن را جداگانه طرح کردم. همچنین ساختار response داده شده مربوط به آمارهای کلیدی در این تصمیم بی تاثیر نبوده است.

این نیز گفتنی است با توجه به ساختار api های بخش دیده‌بان بازار(شامل موارد حقیقی و حقوقی و دیتاهای شناختی هر نماد و همچنین قیمت های تاریخی) که یکجا دیتاها را تحویل می دهد به نظرم حتی خوب است باقی اطلاعاتی را هم که به صورت جداگانه و سهم به سهم از Ticker هر نماد در اختیار کاربر قرار می‌دهیم با یک دستور دیگر به صورت یکجا و کامل نیز در اختیار کاربر قرار دهیم. به نظرم این دو در کنار هم ترکیب کاملی می‌شوند که به طور خاص حالت دوم مناسب فیلترنویسی است و حالت اول مناسب تحلیل یک یا چند سهم به شکل جداگانه است.  

در صورت علاقه‌مندی برای اطلاعات بیشتر از قابلیت های دیده‌بان [این لینک](http://redirectcdn.tsetmc.com/Site.aspx?ParTree=151713) مناسب است.

هر گونه نکته یا پیشنهادی بود در خدمتم.

2022-04-24 18:29 UTC, Glyphack commented
دستت درد نکنه من تا آخر این هفته ریویو رو انجام میدم.

2022-05-03 15:19 UTC, Glyphack commented on pytse_client/data/filter_data/README.md
> +در این بخش آمار کلیدی را در قالب یک نگاشت سه عضوی مشاهده می‌کنید.
خیلی جدول خوبیه از ابزار خاصی استفاده کردی برای ساختش؟

2022-05-03 15:20 UTC, Glyphack commented on pytse_client/data/filter_data/concat.py
> +from key_stats import filter_key_value
اسم این فایل رو میشه بزاریم یه چیزی مثل generate_document.py یا همچین چیزی؟

2022-05-03 15:22 UTC, Glyphack commented on pytse_client/data/filter_data/key_stats.py
> +class KeyStats(object):
این ارث بری از object رو تا جایی که میدونم دیگه نیاز نداریم از یه ورژنی به بعد توی پایتون.
یه کلاسی هم پایتون داره به اسم Enum خواستی نگاه بنداز توی همچین جاهایی بدرد میخوره برای ساخت لیست

2022-05-03 15:35 UTC, Glyphack requested changes
با تشکر. میشه برای این هم فیچر هم تست داشته باشیم؟

2022-05-03 15:35 UTC, Glyphack commented on pytse_client/data/key_stats.py
> +def _request_key_stats() -> str:
فکر کنم این تابع بدون اینکه ریسپانسش داده بشه به _get_list_of_processed_stats استفاده نشه جایی درسته؟ ادغامشون کنیم با هم که خروجی این تابع واضح تر باشه که چی هست؟ برای اینکه خروجی یکم واضح تر باشه چه دیتایی توشه(مثلا من نمیدونم چی داخلشه چون اصلا این API رو ندیدم)‌اگه بشه dataclass بسازیم و فیلدهارو مشخص کنیم خیلی عالی میشه.

2022-05-03 15:35 UTC, Glyphack commented on pytse_client/data/key_stats.py
> +def get_aggregated_key_stats(base_path=None, to_json=False)\
پوشه دیتا رو من تو نظرم بود که کلا چیزای ثابت رو بزاریم که هر چند وقت آپدیت میشه. این تابع رو کاربر میخواد استفاده کنه برای گرفتن اطللاعات بنظرم ببریمش بیرون یه جایی کنار تیکر ودانلود

2022-05-03 16:22 UTC, sfmqrb commented on pytse_client/data/filter_data/README.md
> +در این بخش آمار کلیدی را در قالب یک نگاشت سه عضوی مشاهده می‌کنید.
ابزار خاصی نداشتم ولی github copilot زندگی رو خیلی آسون میکنه برای کارهای تکراری این چنین.

2022-05-03 16:29 UTC, sfmqrb commented on pytse_client/data/key_stats.py
> +def _request_key_stats() -> str:
به نظرم با توجه به خروجی تابع خیلی نمی تونیم از توش دیتاکلاسی در بیاریم ولی ایده خوبیه که توابعی که گفتی رو با هم ترکیب کنیم. یه مقداری زیادی شاید سعی کردم این تابع try catch بنویسم. واقعا هم ایده ای ندارم چه قدر به درد بخوره.

2022-05-03 16:29 UTC, sfmqrb commented on pytse_client/data/key_stats.py
> +def get_aggregated_key_stats(base_path=None, to_json=False)\
ایده ی خوبیه. حتما.

2022-05-03 16:35 UTC, sfmqrb commented
یه سوال کلی هم داشتم. یه کم به نظرم می رسه خروجی دیکشنری ای که متد get_aggregated_key_stats و در صورت سیو در قالب json داره میده با روند پکیج که pandas dataframe کار میکنه در تضاده.
یه کم ملاحظه مموری رو داشتم که این کار رو کردم چون برای خیلی از نماد ها بخشی (بخش بزرگی حتی) از فیلد ها خالیه.
ولی به نظرم تهش بهتره یه خروجی دیتافریم بدم به جای دیکشنری و جیسون و به جای کلیدهای خالی هم مثلا None بذارم. نظرت چیه؟

2022-05-05 15:37 UTC, Glyphack commented
> یه سوال کلی هم داشتم. یه کم به نظرم می رسه خروجی دیکشنری ای که متد get_aggregated_key_stats و در صورت سیو در قالب json داره میده با روند پکیج که pandas dataframe کار میکنه در تضاده. یه کم ملاحظه مموری رو داشتم که این کار رو کردم چون برای خیلی از نماد ها بخشی (بخش بزرگی حتی) از فیلد ها خالیه. ولی به نظرم تهش بهتره یه خروجی دیتافریم بدم به جای دیکشنری و جیسون و به جای کلیدهای خالی هم مثلا None بذارم. نظرت چیه؟


آره موافقم. کلا چیزایی که دیتافریم هم نیست خیلی سوال پرسیده میشه که چطوری باید استفاده بشه بنظرم این هم دیتافریم باشه بهتره.

2022-05-15 13:43 UTC, Glyphack approved these changes

2022-05-15 13:43 UTC, merged