Intraday f index
Glyphack/pytse-client pull request #165
Opened 2022-05-02 11:39 UTC by sfmqrb

#164 
به ایشو بالا رسیدگی شد.
همینطور برای شاخص مالی یک کلاس به نام FinancialIndex تعریف شد تا داده های دیگر مربوط به شاخص ها نیز از آن دریافت شود.
البته می توانستم از http://uat.tsetmc.com/IndexInfo/{financial_index} مثل http://uat.tsetmc.com/IndexInfo/30106839080444358 استفاده کنم ولی چند باری امتحان کردم و به نظرم api قابل اعتمادی نیامد.

2022-05-03 05:27 UTC, Glyphack commented on pytse_client/financial_index/financial_index.py
> +class FinancialIndex:
بنظرم برای این یه تست داشته باشیم که بیاد یکی از شاخص‌هارو بگیره. مثالش توی پوشه تست‌ها هست. چیز زیادی رو نمیشه تست کرد ولی میتونیم بفهمیم که ریکوئست به جای درست میره و اروری نمیگیریم موقع گرفتن دیتا.

2022-05-03 05:27 UTC, Glyphack requested changes
خیلی ممنون همه چیز عالیه تست بنویسیم برای کلاس جدید و مرج کنیم.

2022-05-03 13:17 UTC, sfmqrb commented
سلام @Glyphack 
ممنونم از ریویوت
حتما تست ها رو درست میکنم و می فرستم یه چند روز دیگه.
خیلی خوب میشه وقت کردی بقیه pr ها رو هم یه ریویو بکنی چون مواردی هستن که اگه زودتر مرج بشن کار روی پکیج سریع تر میشه.
الان مثلا این ایشویی که برای باگ باز کردم #166 باید برای حلش توی ticker دست برد که مثلا #162 باهاش مرتبطه و  بهتره تا مرج نشده کاریش نکنم. 
اون بخش دیتاهای فیلترنویسی هم یه بخشی از داده هاش مونده که بگیریم البته مهماش رو گرفتیم ولی اگه زودتر ریویو بشه #163 کمک میکنه به سرعت کار منم.

2022-05-15 13:55 UTC, Glyphack approved these changes

2022-05-15 13:58 UTC, merged