Asks bids
Glyphack/pytse-client pull request #171
Opened 2022-05-15 20:41 UTC by sfmqrb

در اینجا با رسیدگی به ادامه ایشوی #160 به دریافت دیتای لحظه ای order book یا همان ask-bid پرداختم که برای همه تیکرها به صورت یکجا دیتا را دریافت و در قالب یک خروچی csv و پانداس دیتا فریم خروجی میدهد

هنوز البته readme را آپدیت نکرده ام
منتظرم چند کار دیگر که کردم یکجا آپدیت کنم.

2022-05-15 20:42 UTC, sfmqrb commented on pytse_client/ticker_statisticals/utils.py
> +def get_keys_of_market_watch():
این تابع مربوط به ادامه کار پیش رو است که هنوز در این pr به آن رسیدگی نشده است.

2022-05-15 20:43 UTC, sfmqrb commented on pytse_client/ticker_statisticals/utils.py
> +def get_keys_of_client_types():
این تابع مربوط به ادامه کار پیشرو است و هنوز در این پی آر جایی استفاده نشده است.

2022-05-29 00:16 UTC, sfmqrb commented
اول تصمیم گرفته بودم فقط ask-bid در این pr اضافه شود ولی الان pr من شامل همه دیتاهای ارزشمند دیده بان بازاره. :smile:
این تقریبا نهاییه. البته یه جاییش رو میشه ارتقای پرفورمنسی خوبی داد ولی شاید بعدا بیام سراغش یا یکی دیگه بره سرش.
به نظرم آماده مرچ شدنه.
@Glyphack

2022-05-30 05:02 UTC, Glyphack commented
سلام @sfmqrb ببخشید من درگیر امتحانا بودم این رو تا فردا شب چک میکنم حتما مرسی

2022-05-30 07:47 UTC, sfmqrb commented
> سلام @sfmqrb ببخشید من درگیر امتحانا بودم این رو تا فردا شب چک میکنم حتما مرسی
اوکیه آقا عجله ای نیستش راحت باش

2022-07-10 12:10 UTC, Glyphack commented on pytse_client/stats.py
> +def _get_dict_of_client_types(raw_client_types: str):
من دقیق متوجه نشدم این تابع چی کار میکنه.  الان client_type همون حقیقی حقوقیه؟ و ورودی این تابع منظور چیه که  raw_client_type؟
بنظرم این تابع رو میشه فقط یکم اسمش رو تغییر داد و یه مثال از استفادش رو توی کامنت بزاری. 
ولی اون چیزا که معنیشون گنگ میشه رو باید یه جایی لیست کنیم که بدونیم هر کلمه چه معنی میده

2022-07-10 12:11 UTC, Glyphack commented on pytse_client/stats.py
> +def _get_dict_of_market_watch(raw_market_watch: str):
اینجا هم میفهمم که یه لیستی از داریم از اسم سهام به یه اطلاعاتی از دیدبان ولی نمیدونم چه اطلاعاتی؟

2022-07-10 12:15 UTC, Glyphack commented on pytse_client/stats.py
> +def _get_key_stats(session):
بنظرم این توابع رو نیاز نداری، چون الان فقط داره ریکوئست میزنه و دیتا رو برمیگردونه اگر همین یه خط کد ریکوئست رو ببریم توی تابع و همرو با همدیگه یه ترای کچ بزاریم راحت تره خوندنش.
اما کار دیگه‌ای که میشه کرد اینه که این تابع یه مقدار کار بیشتری بکنه، مثلا خود ریسپانس صفحه اطلاعات کلیدی خیلی خروجی راحتی نیست کار کردن باهاش میتونیم یه ذره اطلاعات صفحه رو پارس کنیم و در قالب یه dataclass برگردونیم اینطوری خیلی خروجی تابع خوانا میشه که چیا رو میده و هرجا که به اطلاعات آمار کلیدی نیاز باشه میشه همین تابع رو استفاده کرد.
بنظر من کار دوم رو انجام بدیم. و برای توابع پایینی هم انجام بده لطفا.

2022-07-10 12:17 UTC, Glyphack commented on pytse_client/utils/get_session.py
> +def get_raw_text(url: str, timeout=10):
بنظرم این تابع خیلی کار زیادی داره نمیکنه و داره url رو میگیره یه تابع دیگه صدا میکنه درواقع کارش پاس دادن پارامتره. میتونیم حذفش کنیم که خوندن کد کمتر باشه.

2022-07-10 12:18 UTC, Glyphack commented on pytse_client/utils/symbols.py
> +    parent_dir = os.path.dirname(os.path.abspath(__file__))
ببین یه متغیر به اسم pytse_dir توی فایل کانفیگ هست برای آدرس دادن به فایل‌های برنامه. اینجا بهتره ازون استفاده کنیم چون من حواسم هست که اگر اون فایل جابجا بشه باید اون متغیر هم جابجا بشه اما این فایل ممکنه یه موقع حواسمون نباشه جابجا بشه.

2022-07-10 12:20 UTC, Glyphack requested changes
بازم ببخشید خیلی طول کشید نگاه کنم ولی دیگه هستم از امروز. کامنت‌هارو ببین اگر چیزی رو هم خواستی بیشتر دربارشون حرف بزنیم بهم بگو حتما میتونیم یه جلسه ست کنیم.

2022-07-10 14:29 UTC, sfmqrb commented
> بازم ببخشید خیلی طول کشید نگاه کنم ولی دیگه هستم از امروز. کامنت‌هارو ببین اگر چیزی رو هم خواستی بیشتر دربارشون حرف بزنیم بهم بگو حتما میتونیم یه جلسه ست کنیم.

سلام خوبی؟
اوکیه بابا من خودمم تا دیروز درگیر امتحانا بودم.
این هفته کامنتات رو بررسی می کنم ایشالا 😉

2022-08-07 18:04 UTC, sfmqrb commented on pytse_client/stats.py
> +def _get_dict_of_client_types(raw_client_types: str):
![Screenshot from 2022-08-07 22-32-17](https://user-images.githubusercontent.com/45316558/183304771-4d37a11a-da42-4288-8f34-0ef9361bf8e4.png)

ببین یه همچین چیزیه و خیلی کثیفه.
در واقع بخشی از اون اطلاعات مرتبط با منابع آماری رو دارم از این میگیرم بعد کانورتش میکنم به دیتا فریم

2022-08-07 18:04 UTC, sfmqrb commented on pytse_client/stats.py
> +def _get_dict_of_client_types(raw_client_types: str):
این تابع هم در داخل خود پکیج فقط استفاده میشه.
یعنی کاربرد خارجی ای نداره برای کاربر.

2022-08-07 18:10 UTC, sfmqrb commented on pytse_client/stats.py
> +def _get_dict_of_market_watch(raw_market_watch: str):
اینم مثل بالا تر که گفتم یه استرینگیه از اطلاعات مربوط به دیده بان

2022-08-07 18:11 UTC, sfmqrb commented on pytse_client/stats.py
> +def _get_dict_of_client_types(raw_client_types: str):
توی کامیت https://github.com/Glyphack/pytse-client/pull/171/commits/e79f815a42ac920695a387f7f24f8877caff1377 بهش یه کم اطلاعات اضافه کردم تا خیلی گنگ نباشه.

2022-08-07 18:11 UTC, sfmqrb commented on pytse_client/stats.py
> +def _get_dict_of_market_watch(raw_market_watch: str):
توی کامیت https://github.com/Glyphack/pytse-client/pull/171/commits/e79f815a42ac920695a387f7f24f8877caff1377 بهش یه کم اطلاعات اضافه کردم تا خیلی گنگ نباشه.

2022-08-07 18:27 UTC, sfmqrb commented on pytse_client/stats.py
> +def _get_key_stats(session):
بیبن اینکه دیتاکلاس بکنیم رو من باهات موافقم خوانا تر میشه. 
ولی خیلی تغییرات توی کد زیاد میشه که تا الان دولوپ شده حتی از مرج های قبلی.
کلا من باهاشون مثل دیکشنری برخورد کردم و همه منطق روی این موضوع سواره.
اگر موافق باشی این رو به عنوان یه فیچر nice to have برای تمیز کردن کد پیشنهاد کنیم. ایشالا فرصت کردم خودم میرم سراغش.
به نظرم چون هم توی توابع مربوط به ساخته شدن دیکشنری ها داخل [stats.py](https://github.com/Glyphack/pytse-client/pull/171/files#diff-e15b9dddfca3338ebaceaa3bc48dc69014dcc2fd569840b4d22c0962daefe1f8) کامنت ها خوانایی رو ممکن میکنه و هم درباره key_stats توضیحات مفصلی داخل [این ریدمی](https://github.com/Glyphack/pytse-client/blob/master/pytse_client/ticker_statisticals/README.md) هست و اینکه کد هم کار میکنه :) فعلا از این تغییر بگذریم.

2022-08-07 18:30 UTC, sfmqrb commented on pytse_client/stats.py
> +def _get_key_stats(session):
این توابع رو هم میتونم داخل خود کد بیارم.
فعلا براشون جای جدا گذاشتم اگر بخواد منطق هندل کردن ریکوئست ها همه یه جا جمع بشه درباره stats ها.
مثلا برای هندل کردن ارور های عجیبی که ممکنه بعدا tsetmc بده و خوبه توی اکسپشن ها بعدا هندل بشه.
الان البته فقط جاش رو گذاشتم و اروری خیلی هندل نمیشه و فقط یه پیام چاپ میشه ولی بعدا میشه منطقش رو پیچیده تر کرد.
بازم اگر نظرت اینه که این توابع رو حذف کنم تو این مرحله بگو

2022-08-07 18:35 UTC, sfmqrb commented on pytse_client/utils/get_session.py
> +def get_raw_text(url: str, timeout=10):
done

2022-08-07 18:42 UTC, sfmqrb commented on pytse_client/utils/symbols.py
> +    parent_dir = os.path.dirname(os.path.abspath(__file__))
done

2022-08-07 18:44 UTC, sfmqrb commented
اگر اوکی بود به نظرت تغییرات و مواردی که گفتم بگو قبل مرج فایل داکیومنتیشن پکیج رو با این فیچر های جدید یه آپدیت بکنم تا قابل استفاده باشه برای یوزر.
@Glyphack

2022-08-07 18:46 UTC, Glyphack commented
سلام دستت درد نکنه فرد بعد از ظهر چک میکنم

2022-08-08 16:40 UTC, Glyphack commented
@sfmqrb همه چیز عالیه میتونی داکیومنت رو هم آپدیت کنی؟

2022-08-08 16:57 UTC, sfmqrb commented
>

2022-08-08 16:59 UTC, sfmqrb commented
آقا دستم خورد کلوز کردم
میتونی اوپن کنی؟
@Glyphack

2022-08-08 17:00 UTC, sfmqrb commented
> @sfmqrb همه چیز عالیه میتونی داکیومنت رو هم آپدیت کنی؟

حله حتما

2022-08-08 17:34 UTC, sfmqrb commented
حله @Glyphack 
آماده مرجه

2022-08-08 17:35 UTC, merged