Update symbols_name.json
Glyphack/pytse-client pull request #32
Opened 2020-10-13 17:04 UTC by thisismz

لیست بروز تمامی نماد ها همراه با اختیار معاملات

2020-10-14 07:17 UTC, Glyphack commented on pytse_client/data/symbols_name.json
> +  "تابان01":"29970481413277747",
یه سوالی درباره این نمادهایی که آخرش عدد هست دارم. اینا چرا آخرشون عدد داره؟ و اینکه چرا سابقه این نماد‌ها با بقیه فرق داره(تعداد بسیار کمی روز با معامله داشتن.

2020-10-14 07:21 UTC, Glyphack requested changes
مرسی. این خیلی کامل‌تر از چیزیه که داشتیم.
این لیست تمام نماد‌های همه‌ی بازار هاست؟ از صفحه‌ی دیده‌بان بازار جمع شده؟

2020-10-14 15:02 UTC, thisismz commented on pytse_client/data/symbols_name.json
> +  "تابان01":"29970481413277747",
سلام اینا اوراق اجاره ای هستن دقیقا در بورس چه کاربردی دارن آشنایی ندارم

2021-01-12 18:57 UTC, Mgavahi commented on pytse_client/data/symbols_name.json
> +  "تابان01":"29970481413277747",
سلام من فایل دیتا روکامل کردم ولی وقتی اونو اپلود کردم نام های جدید رو توی دوتا خط گذاشت و اگه امکان داره اون فایل جیسون رو مرتب کنید

2021-01-12 19:04 UTC, Mgavahi commented
سلام من فایل دیتا روکامل کردم ولی وقتی اونو اپلود کردم نام های جدید رو توی دوتا خط گذاشت و اگه امکان داره اون فایل جیسون رو مرتب کنید

2021-01-21 16:55 UTC, paysheen approved these changes

2021-02-02 12:26 UTC, closed without merging